CREATE TABLE [dbo].SteamAccount(
	[SteamId64] [bigint] NOT NULL,
	[SteamId3] [bigint] NOT NULL,
	[DiscordId] [bigint] NOT NULL
PRIMARY KEY CLUSTERED 
(
	[SteamId64] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
