namespace Models.Enums
{
    public enum FightTypesEnum
    {
        WvW = 0,
        Vale = 1,
        Gorseval = 2,
        Sabetha = 3,
        Sloth = 4,
        Trio = 5,
        Matthias = 6,
        Escort = 7,
        KC = 8,
        TC = 9,
        Xera = 10,
        Cairn = 11,
        MO = 12,
        Samarog = 13,
        Deimos = 14,
        SH = 15,
        River = 16,
        BK = 17,
        EoS = 18,
        SoD = 19,
        Dhuum = 20,
        CA = 21,
        Largos = 22,
        Qadim = 23,
        Adina = 24,
        Sabir = 25,
        Peerless = 26,
        AH = 27,
        XJJ = 28,
        KO = 29,
        HT = 30,
        OLC = 31,
        CO = 32,
        ToF = 33,
        MAMA = 34,
        Siax = 35,
        Ensolyss = 36,
        Skorvald = 37,
        Artsariiv = 38,
        Arkk = 39,
        AiEle = 40,
        AiDark = 41,
        AiBoth = 42,
        Kanaxai = 43,
        UNKN = short.MaxValue
    }
}
