services:
  donbot:
    image: ghcr.io/loganwal/gw2-donbot:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/app/Logs

  donbot-api:
    image: ghcr.io/loganwal/gw2-donbot-api:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./logs-api:/app/Logs
      - /tmp/donbot:/tmp/donbot

  donbot-web:
    image: ghcr.io/loganwal/gw2-donbot-web:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - donbot-api

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - REPO_USER=${GHCR_USER}
      - REPO_PASS=${GHCR_TOKEN}
      - DOCKER_API_VERSION=1.44
