services:
  donbot:
    image: donbot-local
    profiles: ["bot"]
    build:
      context: .
      dockerfile: Dockerfile

  donbot-api:
    ports:
      - "5001:8080"
    environment:
      - Discord__RedirectUri=http://localhost:5001/auth/discord/callback

  watchtower:
    profiles: ["disabled"]
