namespace DonBot.Models.Enums;

public enum FightTypesEnum
{
    WvW = 0,
    Vale = 1, // wing 1
    Gorseval = 2, // wing 1
    Sabetha = 3, // wing 1
    Sloth = 4, // wing 2
    Trio = 5, // wing 2
    Matthias = 6, // wing 2
    Escort = 7, // wing 3
    Kc = 8, // wing 3
    Tc = 9, // wing 3
    Xera = 10, // wing 3
    Cairn = 11, // wing 4
    Mo = 12, // wing 4
    Samarog = 13, // wing 4
    Deimos = 14, // wing 4
    Sh = 15, // wing 5
    River = 16, // wing 5
    Bk = 17, // wing 5
    EoS = 18, // wing 5
    SoD = 19, // wing 5
    Dhuum = 20, // wing 5
    Ca = 21, // wing 6
    Largos = 22, // wing 6
    Qadim = 23, // wing 6
    Adina = 24, // wing 7
    Sabir = 25, // wing 7
    Peerless = 26, // wing 7
    Ah = 27, // EoD Strike
    Xjj = 28, // EoD Strike
    Ko = 29, // EoD Strike
    Ht = 30, // EoD Strike
    Olc = 31, // Core Strike
    Co = 32, // Soto Strike
    ToF = 33, // Soto Strike
    Mama = 34, // Fractal
    Siax = 35, // Fractal
    Ensolyss = 36, // Fractal
    Skorvald = 37, // Fractal
    Artsariiv = 38, // Fractal
    Arkk = 39, // Fractal
    AiEle = 40, // Fractal
    AiDark = 41, // Fractal
    AiBoth = 42, // Fractal
    Kanaxai = 43, // Fractal
    Greer = 44, // wing 8
    Decima = 45, // wing 8
    Ura = 46, // wing 8
    Icebrood = 47, // Icebrood Strike
    Fraenir = 48, // Icebrood Strike
    Kodan = 49, // Icebrood Strike
    Whisper = 50, // Icebrood Strike
    Boneskinner = 51, // Icebrood Strike
    Eparch = 52, // Fractal
    Spirit = 53, // wing 1
    Shadow = 54, // Fractal
    Kela = 55, // wing 9
    Golem = 32766, // Golem
    Unkn = short.MaxValue,
}