// <auto-generated />
using System;
using DonBot.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DonBot.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DonBot.Models.Entities.Account", b =>
                {
                    b.Property<long>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DiscordId"));

                    b.Property<decimal>("AvailablePoints")
                        .HasPrecision(16, 3)
                        .HasColumnType("numeric(16,3)");

                    b.Property<DateTime?>("LastWvwLogDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Points")
                        .HasPrecision(16, 3)
                        .HasColumnType("numeric(16,3)");

                    b.Property<decimal>("PreviousPoints")
                        .HasPrecision(16, 3)
                        .HasColumnType("numeric(16,3)");

                    b.HasKey("DiscordId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.FightLog", b =>
                {
                    b.Property<long>("FightLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FightLogId"));

                    b.Property<long>("FightDurationInMs")
                        .HasColumnType("bigint");

                    b.Property<int>("FightMode")
                        .HasColumnType("integer");

                    b.Property<decimal>("FightPercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int?>("FightPhase")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FightStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("FightType")
                        .HasColumnType("smallint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("FightLogId");

                    b.ToTable("FightLog", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.FightLogRawData", b =>
                {
                    b.Property<long>("FightLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawBarrierData")
                        .HasMaxLength(104857600)
                        .HasColumnType("text");

                    b.Property<string>("RawFightData")
                        .HasMaxLength(104857600)
                        .HasColumnType("text");

                    b.Property<string>("RawHealingData")
                        .HasMaxLength(104857600)
                        .HasColumnType("text");

                    b.HasKey("FightLogId");

                    b.ToTable("FightLogRawData", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.FightsReport", b =>
                {
                    b.Property<long>("FightsReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("FightsReportId"));

                    b.Property<DateTime?>("FightsEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FightsStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.HasKey("FightsReportId");

                    b.ToTable("FightsReport", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.Guild", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GuildId"));

                    b.Property<long?>("AdvanceLogReportChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AnnouncementChannelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("AutoAggregateLogs")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoReplySingleLog")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoSubmitToWingman")
                        .HasColumnType("boolean");

                    b.Property<long?>("DiscordGuildMemberRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DiscordSecondaryMemberRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DiscordVerifiedRoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("GuildName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gw2GuildMemberRoleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Gw2SecondaryMemberRoleIds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long?>("LogDropOffChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LogReportChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PveLeaderboardChannelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PveLeaderboardEnabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("RaidAlertChannelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("RaidAlertEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("RemoveSpamEnabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("RemovedMessageChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StreamLogChannelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WvwLeaderboardChannelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("WvwLeaderboardEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId");

                    b.ToTable("Guild", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.GuildQuote", b =>
                {
                    b.Property<long>("GuildQuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GuildQuoteId"));

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<string>("Quote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("GuildQuoteId");

                    b.ToTable("GuildQuote", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.GuildWarsAccount", b =>
                {
                    b.Property<Guid>("GuildWarsAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("DiscordId")
                        .HasColumnType("bigint");

                    b.Property<int>("FailedApiPullCount")
                        .HasColumnType("integer");

                    b.Property<string>("GuildWarsAccountName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GuildWarsApiKey")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GuildWarsGuilds")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("World")
                        .HasColumnType("integer");

                    b.HasKey("GuildWarsAccountId");

                    b.ToTable("GuildWarsAccount", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.LogUpload", b =>
                {
                    b.Property<long>("LogUploadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogUploadId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscordId")
                        .HasColumnType("bigint");

                    b.Property<string>("DpsReportUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long?>("FightLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SubmitToWingman")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LogUploadId");

                    b.ToTable("LogUpload", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.PlayerFightLog", b =>
                {
                    b.Property<long>("PlayerFightLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlayerFightLogId"));

                    b.Property<decimal>("AlacDuration")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<long>("BarrierGenerated")
                        .HasColumnType("bigint");

                    b.Property<long>("BarrierMitigation")
                        .HasColumnType("bigint");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("Cleanses")
                        .HasColumnType("bigint");

                    b.Property<long>("Cleave")
                        .HasColumnType("bigint");

                    b.Property<long>("Damage")
                        .HasColumnType("bigint");

                    b.Property<long>("DamageDownContribution")
                        .HasColumnType("bigint");

                    b.Property<long>("DamageTaken")
                        .HasColumnType("bigint");

                    b.Property<long>("Deaths")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DistanceFromTag")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)");

                    b.Property<long>("Downs")
                        .HasColumnType("bigint");

                    b.Property<long>("FightLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("GuildWarsAccountName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Healing")
                        .HasColumnType("bigint");

                    b.Property<long>("Interrupts")
                        .HasColumnType("bigint");

                    b.Property<long>("Kills")
                        .HasColumnType("bigint");

                    b.Property<long>("NumberOfBoonsRipped")
                        .HasColumnType("bigint");

                    b.Property<long>("NumberOfHitsWhileBlinded")
                        .HasColumnType("bigint");

                    b.Property<long>("NumberOfMissesAgainst")
                        .HasColumnType("bigint");

                    b.Property<long>("NumberOfTimesBlockedAttack")
                        .HasColumnType("bigint");

                    b.Property<long>("NumberOfTimesEnemyBlockedAttack")
                        .HasColumnType("bigint");

                    b.Property<decimal>("QuicknessDuration")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("ResurrectionTime")
                        .HasColumnType("integer");

                    b.Property<decimal>("StabGenOffGroup")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("StabGenOnGroup")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<long>("Strips")
                        .HasColumnType("bigint");

                    b.Property<long>("SubGroup")
                        .HasColumnType("bigint");

                    b.Property<long?>("TimeOfDeath")
                        .HasColumnType("bigint");

                    b.Property<int>("TimesDowned")
                        .HasColumnType("integer");

                    b.Property<long>("TimesInterrupted")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerFightLogId");

                    b.ToTable("PlayerFightLog", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.PlayerFightLogMechanic", b =>
                {
                    b.Property<long>("PlayerFightLogMechanicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlayerFightLogMechanicId"));

                    b.Property<long>("MechanicCount")
                        .HasColumnType("bigint");

                    b.Property<string>("MechanicName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("PlayerFightLogId")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerFightLogMechanicId");

                    b.HasIndex("PlayerFightLogId");

                    b.ToTable("PlayerFightLogMechanic", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.PlayerRaffleBid", b =>
                {
                    b.Property<int>("RaffleId")
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    b.Property<long>("DiscordId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<decimal>("PointsSpent")
                        .HasPrecision(16, 3)
                        .HasColumnType("numeric(16,3)");

                    b.HasKey("RaffleId", "DiscordId");

                    b.ToTable("PlayerRaffleBid", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.Raffle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RaffleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Raffle", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.RotationAnomaly", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("AverageInterval")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ConsecutiveCasts")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FightUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("MaxDeviation")
                        .HasColumnType("decimal(10, 3)");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("RotationAnomaly", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.ScheduledEvent", b =>
                {
                    b.Property<long>("ScheduledEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ScheduledEventId"));

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<short>("Day")
                        .HasColumnType("smallint");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<short>("Hour")
                        .HasColumnType("smallint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<short>("RepeatIntervalDays")
                        .HasColumnType("smallint");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UtcEventTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduledEventId");

                    b.ToTable("ScheduledEvent", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.SteamAccount", b =>
                {
                    b.Property<long>("SteamId64")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SteamId64"));

                    b.Property<long>("DiscordId")
                        .HasColumnType("bigint");

                    b.Property<long>("SteamId3")
                        .HasColumnType("bigint");

                    b.HasKey("SteamId64");

                    b.ToTable("SteamAccount", (string)null);
                });

            modelBuilder.Entity("DonBot.Models.Entities.FightLogRawData", b =>
                {
                    b.HasOne("DonBot.Models.Entities.FightLog", null)
                        .WithOne()
                        .HasForeignKey("DonBot.Models.Entities.FightLogRawData", "FightLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DonBot.Models.Entities.PlayerFightLogMechanic", b =>
                {
                    b.HasOne("DonBot.Models.Entities.PlayerFightLog", null)
                        .WithMany()
                        .HasForeignKey("PlayerFightLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
